[buildPlans.IosevkaCrownOfStars]
family = "Iosevka Crown of Stars"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaCrownOfStars.variants.design]
one = "base-flat-top-serif"
two = "straight-neck-serifed"
three = "flat-top-serifed"
four = "semi-open-serifed"
five = "oblique-arched-serifed"
six = "closed-contour"
seven = "curly-serifed-crossbar"
eight = "crossing-asymmetric"
nine = "closed-contour"
zero = "oval-broken-slash"
capital-a = "curly-top-serifed"
capital-b = "more-asymmetric-interrupted-bilateral-serifed"
capital-c = "bilateral-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifed-capped"
capital-f = "serifed-capped"
capital-g = "toothed-serifed-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-j = "descending-flat-hook-serifed"
capital-k = "symmetric-touching-full-serifed"
capital-l = "serifed"
capital-m = "slanted-sides-flat-bottom-serifed"
capital-n = "asymmetric-serifed"
capital-p = "open-serifed"
capital-q = "open-swash"
capital-r = "standing-open-serifed"
capital-s = "bilateral-serifed"
capital-u = "toothed-serifed"
capital-v = "straight-serifed"
capital-w = "straight-vertical-sides-flat-top-serifed"
capital-x = "straight-serifed"
capital-y = "curly-serifed"
capital-z = "straight-serifed-with-horizontal-crossbar"
a = "double-storey-hook-inward-serifed-tailed"
b = "bottom-cut-serifed"
c = "bilateral-inward-serifed"
d = "toothed-serifed"
e = "flat-crossbar"
f = "extended"
g = "double-storey-open"
h = "straight-serifed"
i = "zshaped"
j = "diagonal-tailed-serifed"
k = "symmetric-touching-full-serifed"
l = "zshaped"
m = "earless-single-arch-serifed"
n = "earless-corner-tailed-serifed"
p = "eared-serifed"
q = "top-cut-straight-serifed"
r = "corner-hooked-top-serifed"
s = "bilateral-serifed"
t = "flat-hook-asymmetric-short-neck"
u = "toothed-serifed"
v = "curly-serifed"
w = "straight-vertical-sides-flat-top-serifed"
x = "semi-chancery-straight-serifed"
y = "straight-serifed"
z = "straight-serifed-with-horizontal-crossbar"
capital-eszet = "corner-serifed"
long-s = "bent-hook-double-serifed-xh"
eszet = "traditional-flat-hook-dual-serifed"
lower-eth = "straight-bar"
capital-thorn = "asymmetric-serifed"
lower-alpha = "barred-earless-rounded-serifed"
capital-delta = "curly"
lower-delta = "flat-top"
lower-eta = "serifed"
lower-kappa = "symmetric-touching-bottom-right-serifed"
capital-lambda = "curly-tri-serifed"
lower-lambda = "curly-turn"
lower-mu = "toothed-serifed"
lower-nu = "casual"
lower-pi = "small-capital"
lower-upsilon = "straight-serifed"
lower-chi = "semi-chancery-straight-serifed"
lower-psi = "serifed"
partial-derivative = "straight-bar"
cyrl-ve = "standard-interrupted-bilateral-serifed"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ze = "bilateral-serifed"
cyrl-ze = "bilateral-serifed"
cyrl-capital-ka = "symmetric-connected-tri-serifed"
cyrl-em = "slanted-sides-flat-bottom-serifed"
cyrl-capital-er = "open-serifed"
cyrl-ef = "split-serifed"
cyrl-capital-e = "bilateral-serifed"
cyrl-e = "bilateral-serifed"
cyrl-capital-ya = "straight-open-serifed"
cyrl-ya = "straight-open-tailed-serifed"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
braille-dot = "square"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "high"
paren = "flat-arc"
brace = "curly"
ampersand = "flat-top"
at = "fourfold"
dollar = "interrupted"
cent = "slanted-through"
percent = "rings-continuous-slash-also-connected"
question = "corner"
lig-ltgteq = "slanted"
lig-neq = "more-slanted-dotted"

[buildPlans.IosevkaCrownOfStars.variants.italic]
one = "base-long-top-serif"
two = "curly-neck-serifed"
three = "two-arcs"
four = "closed-serifless"
five = "oblique-flat-serifed"
six = "open-contour"
seven = "bend-serifed-crossbar"
eight = "crossing-asymmetric"
nine = "open-contour"
zero = "oval-broken-reverse-slash"
capital-a = "round-top-base-serifed"
capital-b = "more-asymmetric-unilateral-serifed"
capital-c = "unilateral-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothed-inward-serifed-hooked"
capital-h = "top-left-serifed"
capital-i = "short-serifed"
capital-j = "descending-serifed"
capital-k = "curly-top-left-and-bottom-right-serifed"
capital-l = "motion-serifed"
capital-m = "slanted-sides-hanging-motion-serifed"
capital-n = "asymmetric-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "closed-swash"
capital-r = "standing-top-left-and-bottom-right-serifed"
capital-s = "unilateral-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-rounded-bilateral-motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "curly-almost-flat-top-serifed"
capital-x = "curly-bilateral-motion-serifed"
capital-y = "curly-motion-serifed"
capital-z = "curly-bottom-serifed-with-crossbar"
a = "single-storey-top-cut-tailed"
b = "toothless-corner-serifed"
d = "toothless-corner-serifed"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey"
h = "tailed-motion-serifed"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "curly-top-left-and-bottom-right-serifed"
l = "serifed-diagonal-tailed"
m = "earless-rounded-double-arch-short-leg-tailed-serifed"
n = "earless-rounded-tailed-serifed"
p = "earless-corner-serifless"
q = "earless-corner-tailed-serifless"
r = "hookless-top-serifed"
s = "unilateral-serifed"
t = "diagonal-tailed-asymmetric-short-neck2"
u = "toothless-rounded-serifed"
v = "cursive-serifed"
w = "straight-vertical-sides-flat-top-motion-serifed"
x = "semi-chancery-curly-serifed"
y = "curly-motion-serifed"
z = "curly-top-serifed-with-crossbar"
capital-eszet = "rounded-serifed"
long-s = "flat-hook-descending-middle-serifed-xh"
eszet = "longs-s-lig-tailed-middle-serifed-xh"
lower-eth = "curly-bar"
capital-thorn = "asymmetric-motion-serifed"
lower-thorn = "motion-serifed"
lower-alpha = "barred-earless-rounded-serifed"
lower-beta = "cursive"
capital-gamma = "top-right-serifed"
capital-delta = "curly"
lower-delta = "flat-top"
lower-eta = "serifed"
lower-theta = "cursive"
lower-kappa = "symmetric-connected-top-right-serifed"
capital-lambda = "curly-top-serifed"
lower-lambda = "curly-tailed-turn"
lower-mu = "toothless-rounded-serifed"
lower-nu = "curly"
lower-xi = "rounded"
lower-pi = "tailed"
lower-tau = "semi-tailed"
lower-upsilon = "casual-serifed"
lower-phi = "neo-hellenic"
lower-chi = "semi-chancery-curly-serifed"
lower-psi = "serifed"
partial-derivative = "closed-contour"
cyrl-a = "single-storey-earless-corner-serifless"
cyrl-ve = "standard-unilateral-serifed"
cyrl-capital-zhe = "cursive"
cyrl-zhe = "cursive"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-el = "tailed"
cyrl-em = "slanted-sides-flat-bottom-motion-serifed"
cyrl-capital-en = "top-left-bottom-right-serifed"
cyrl-en = "top-left-bottom-right-serifed"
cyrl-capital-er = "closed-motion-serifed"
cyrl-er = "eared-motion-serifed"
cyrl-capital-u = "curly-turn-motion-serifed"
cyrl-u = "straight-turn-motion-serifed"
cyrl-ef = "split-cursive"
cyrl-che = "tailed"
cyrl-yeri = "cursive"
cyrl-yery = "cursive-tailed"
cyrl-capital-e = "unilateral-serifed"
cyrl-e = "unilateral-serifed"
cyrl-capital-ya = "curly-motion-serifed"
cyrl-ya = "curly-motion-serifed"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
braille-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "high"
paren = "flat-arc"
brace = "curly"
ampersand = "et-tailed"
at = "fourfold-solid-inner-tall"
dollar = "slanted-interrupted"
cent = "slanted-through"
percent = "rings-continuous-slash-also-connected"
question = "corner-flat-hooked"
pilcrow = "curved"
lig-ltgteq = "slanted"

[buildPlans.IosevkaCrownOfStars.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCrownOfStars.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCrownOfStars.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCrownOfStars.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCrownOfStars.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCrownOfStars.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaCrownOfStars.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCrownOfStars.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCrownOfStars.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

